#!/bin/bash

case "$1" in
    "latex")   exts=("aux" "bbl" "bcf" "blg" "fdb_latexmk" "fls" "log" "nav" "out" "run.xml" "snm" "synctex.gz" "toc" "vrb" "xdv") ;;
    "ocaml")   exts=("out" "cmi" "cmo" "o") ;;
    "haskell") exts=("hi"  "o") ;;
    *)       notify-send 'Unkonw Choice' 'The language is not taken from the list' --icon=dialog-error ;;
esac

for element in "${exts[@]}"
do
    echo "*.$element" >> .gitignore
done
