#!/bin/bash


case "$1" in
    "area")   scrot -s;;
    "focus")  scrot --focused;;
    *)        notify-send 'Unkonw Choice' 'Not a valid `scrot` option' --icon=dialog-error;;
esac

notify-send 'Scrot' 'Screenshot taken'

