#!/bin/bash

source ~/git/scripts/rofi_env.sh

msg="Cleaner"

options=(
    "latex"
    "ocaml"
    "haskell"
)

run_rofi() {
    for str in ${options[@]}; do echo $str; done | rofi_dmenu "$msg"
}

case "$(run_rofi)" in
    "latex")   exts=".(aux|bbl|bcf|blg|fdb_latexmk|fls|log|nav|out|run.xml|snm|synctex.gz|toc|vrb|xdv|_minted-*|idx|ind|ilg)$"
               ;;
    "ocaml")   exts=".(out|cmi|cmo|cmx|o)$"
               ;;
    "haskell") exts=".(hi|o)$"
               ;;
    *)
        notify-send 'Unkonw Choice' 'The language is not taken from the list' --icon=dialog-error
        exit 0
        ;;
esac

sel=$(fd -IH --max-depth=1 -p ${exts})

echo $sel

if [[ "$(rofi_yesno)" == "$rofi_yes" ]]; then
    rm -rf $sel
fi
