#!/bin/zsh

dp1="DP-4-1"      # `DP-1` port of my dock
dp2="DP-4-2"      # `DP-2` port of my dock
dp3="DP-4-3"      # `HDMI` port of my dock
dp5="DP-5"        # `HDMI` from adaptater
intern="eDP-1"    # `main`

xrandr --dpi 144

extras_monitors=$(xrandr -q | rg  'DP-.* connected' | awk '{print $1}' | sed '/eDP-1/d')

notify() {
    notify-send 'Xrandr' $1
}

monitor_remove() {
    for extra_monitor in $extras_monitors
    do
        bspc monitor $intern -a Desktop # Temp desktop because one desktop required per monitor

        # Move everything to external monitor to reorder desktops
        for desktop in $(bspc query -D -m $intern)
        do
            bspc desktop $desktop --to-monitor $extra_monitor
        done

        # Now move everything back to internal monitor
        bspc monitor $extra_monitor -a Desktop # Temp desktop

        for desktop in $(bspc query -D -m $extra_monitor)
        do
            bspc desktop $desktop --to-monitor $intern
        done

        bspc desktop Desktop --remove # Remove temp desktops
    done
}

case $extras_monitors in
    $dp3)
        xrandr --output "$dp3" --primary --scale 2x2 --pos 0x0 --auto \
               --output "$intern" --pos 3840x0 --auto

        bspc monitor $dp3    -d 1 2 3 4 5
        bspc monitor $intern -d 6 7 8 9 0

        notify '[Home] layout selected'
        ;;
    $dp1*$dp2)
        xrandr --output "$dp1" --primary --scale 1.5x1.5 --pos 0x0 --auto \
               --output "$dp2" --scale 1.5x1.5 --pos 5120x0 --auto \
               --output "$intern" --off

        bspc monitor eDP-1 --remove
        bspc monitor $dp1 -d 1 2 3 4 5
        bspc monitor $dp2 -d 6 7 8 9 0

        notify '[Office] layout selected'
        ;;
    $dp5)
        xrandr --output "$intern" --mode 1920x1080 --output "$dp5" --same-as eDP-1
        bspc monitor $intern -d 1 2 3 4 5 6 7 8 9
        notify '[S190] layout selected'
        ;;
    "")
        monitor_remove

        xrandr --output "$intern" --pos 0x0 --mode 2560x1600 --scale 1x1 --primary
        bspc monitor $intern -d 1 2 3 4 5 6 7 8 9

        notify '[Labtop only] layout selected'
        ;;
    *) notify '[Unsupported] layout'
        ;;
esac

feh --bg-fill --no-fehbg ~/.wallpaper/Hopper-Gas-1940.png
